# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42fc7a3df43e5e23c77774df5e1381f1d1085ace0adb081636b61a9a0c9d5604f4cc4df15f824c24038b49d8121757fbf9e47c20aeb1c3ed797b00b2ec8ae82b

test:
  secret_key_base: e281ea74a90c2e92ec23a20c9a04093d06ddbdb2c5f6fe8d755f61fa886b15671ec1625964f095ed46cbd0f25793d99272de6b9a7e5e78265e60a9dd367275eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
